config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path_names:{
    sign_up: ''
  }

  resources :users
  resources :notifications

  root to: 'dashboard#index'

  namespace :api do
    mount_devise_token_auth_for 'User', at: 'auth', as: 'users', controllers: {
      sessions: 'users/sessions'
    }
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def index
    if current_user.try(:admin?)
      @users = User.all
      @notifications = Notification.all
      @monthly_growth = ((User.where("created_at > ?", 1.month.ago).count / User.all.count.to_f) * 100).round
    else
      sign_out(current_user)
      redirect_to "/users/sign_in", notice: "Must be an admin user to login at this dashboard. Please checkout our mobile app for our members."
    end
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.haml
%div{:style => " margin-top: 3vh; padding:15px;"}
  .row
    .col-lg-3.col-md-3.col-sm-6.col-xs-12.col-lg-offset-3.col-md-offset-3
      .dashboard-stat.dashboard-stat-v2.red{:href => "#"}
        .visual
          %i.fa.fa-line-chart
        .details
          .number
            +
            %span{"data-counter" => "counterup", "data-value" => @monthly_growth}=@monthly_growth
            \%
          .desc Monthly Growth


    .col-lg-3.col-md-3.col-sm-6.col-xs-12
      .dashboard-stat.dashboard-stat-v2.purple{:href => "#"}
        .visual
          %i.fa.fa-envelope
        .details
          .number
            %span{"data-counter" => "counterup", "data-value" => Notification.count}=Notification.count
          .desc Push Notifications

    .col-lg-3.col-md-3.col-sm-6.col-xs-12
      .dashboard-stat.dashboard-stat-v2.green{:href => "#"}
        .visual
          %i.fa.fa-users
        .details
          .number
            %span{"data-counter" => "counterup", "data-value" => User.count}=User.count
          .desc Total Users

.col-sm-12
  / BEGIN BORDERED TABLE PORTLET
  .portlet.light.portlet-fit
    .portlet-title
      .caption
        %span.caption-subject.sbold.uppercase{:style => "color: #455A64 !important"} Users
    .portlet-body{:style => "padding-top: 15px;"}
      .table-scrollable.table-scrollable-borderless{:style => "overflow: visible !imporant;"}
        %table#users_table.table.table-hover.table-light
          %thead
            %tr.uppercase
              %th{:style => " color: #455A64"} #
              %th{:style => " color: #455A64"} Email
              %th{:style => " color: #455A6A"} Since
              %th{:style => " color: #455A64"} Device Token
          %tbody
            - @users.each_with_index  do | user, index |
              %tr
                %td= index+1
                %td= user.email
                %td= user.created_at.strftime("%m/%d/%Y at %I:%M%p")
                %td
                  - if user.device_token.present?
                    %span.label.label-sm.label-success Yes
                  - else
                    %span.label.label-sm.label-danger No

.col-sm-12
  / BEGIN BORDERED TABLE PORTLET
  .portlet.light.portlet-fit
    .portlet-title
      .caption
        %span.caption-subject.sbold.uppercase{:style => "color: #455A64 !important"} Push notifications
      .actions
        .btn-group.btn-group-devided
          = link_to 'Create notification', new_notification_path, class:"btn green btn-outline btn-sm active", style: "color: white;text-decoration:none"
    .portlet-body{:style => "padding-top: 0;"}
      .table-scrollable.table-scrollable-borderless{:style => "overflow: visible !important;"}
        %table#push_notifications_index_table.table.table-hover.table-light
          %thead
            %tr.uppercase
              %th{:style => "color: #455A64"} #
              %th{:style => "color: #455A64"} Message
              %th{:style => "color: #455A64"} Sent by
              %th{:style => "text-align:center; color: #455A64"} Sent at
              %th{:style => "text-align:center; color: #455A64"} Actions
          %tbody
            - @notifications.each_with_index  do |notification, index|
              %tr
                %td= index+1
                %td= notification.message
                %td= User.find(notification.user_id).email
                %td{:style => "text-align:center; color: #455A64"}= notification.created_at.strftime("%m/%d/%Y at %I:%M%p")
                %td
                  .actions{:style => "text-align:center"}
                    .btn-group
                      %a.btn.dark.btn-outline.btn-circle.btn-sm{"data-close-others" => "true", "data-hover" => "dropdown", "data-toggle" => "dropdown", :href => "javascript:;", :style => "text-decoration: none;"}
                        Actions
                        %i.fa.fa-angle-down
                      %ul.dropdown-menu.pull-right{:style => "text-align:center"}
                        %li
                          = link_to 'View', notification
                        %li.divider
                        %li
                          = link_to 'Delete', notification, method: :delete, data: { confirm: 'Are you sure?' }