config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path_names:{
    sign_up: ''
  }

  resources :users
  resources :notifications

  root to: 'dashboard#index'

  namespace :api do
    mount_devise_token_auth_for 'User', at: 'auth', as: 'users', controllers: {
      sessions: 'users/sessions'
    }
  end

end

app/models/notification.rb
require 'open-uri'
require 'net/http'

class Notification < ApplicationRecord
  belongs_to :user
  after_save :upload_notification_to_ionic

  validates :message, presence: true
  validates :tokens,  presence: true

private
  def upload_notification_to_ionic
    puts "Push Notification Created: Sent-to: self.tokens.to_json"

    params = {
      "tokens" => self.tokens,
      "profile" => ENV['IONIC_PUSH_ENV'],
      "notification":{
        "message": self.message,
        "android":{
          "title": "HTI",
          "sound": "true"
        },
         "ios": {
              "title": "HTI",
              "sound": "true"
              # ,
              # "badge": 1
            }
      }
    }

    uri = URI.parse('https://api.ionic.io/push/notifications')
    https = Net::HTTP.new(uri.host,uri.port)
    https.use_ssl = true
    req = Net::HTTP::Post.new(uri.path)
    req['Authorization'] = ENV['IONIC_API_TOKEN']
    req['Content-Type'] = 'application/json'
    req.body = params.to_json
    res = https.request(req)
    puts res.body
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController

  before_action :authenticate_admin

  def index
    @notifications = Notification.all
  end

  def show
    @notification = Notification.find(params[:id])
  end

  def new
    @notification = Notification.new
    @users = User.all
    # @users = User.where.not('device_token' => nil)
  end

  # def edit
  # end

  def create
    @users = User.all

    @notification = Notification.new(notification_params)
    @notification.user_id = current_user.id

    @notification.sent_to = params[:tokens]

    if @notification.sent_to.present?
      @notification.sent_to.each do |t|
        device_token = @users.find(t).device_token
        @notification.tokens.push(device_token) unless device_token.nil?
      end

      respond_to do |format|
        if @notification.save
          format.html { redirect_to root_path, notice: 'Push Notification was successfully created.' }
        else
          format.html { render :new }
        end
      end

    else
      respond_to do |format|
        format.html { redirect_to root_path, notice: 'Error: Please select at least one user to send a push notification.' }
      end
    end
  end

  def destroy
    Notification.find(params[:id]).destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Push Notification was successfully destroyed.' }
    end
  end

  private

  def notification_params
    params.fetch(:notification, {}).permit(:message, :sent_to, :user_id, tokens:[])
  end

  def authenticate_admin
    unless current_user.try(:admin?)
      render json: {
        status: :unathorized
      }.to_json
    end
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/index.html.haml
%h1 Notifications

- @notifications.each do |notification|

  = link_to "Notification#{notification.id}", notification_path(notification)

app/views/notifications/new.html.haml
.col-xs-12.col-lg-8.col-lg-offset-2{:style => " margin-top: 3vh; padding:15px;"}
  .portlet.light
    .portlet-title
      .caption.font-red-sunglo
        %span.caption-subject.bold.uppercase{:style => "font-size:24px"} Send Push Notification
        %br/
      .actions
        = link_to :back, :class => "btn btn-circle btn-icon-only red" do
          %i.fa.fa-arrow-left
          
    .portlet-body.form
      = form_for(@notification) do |f|
        - if @notification.errors.any?
          %div{:style => "visibility: hidden; height:0;"}
            = flash[:notice] = @notification.errors.full_messages
        .form-group.form-md-line-input.form-md-floating-label
          / <textarea class="form-control" rows="3" maxlength="256"></textarea>
          = f.text_area :message, class: "form-control", rows: 3, maxlength: 256
          %label{:for => "form_control_1"} Message Text
          %span.help-block Push Notification has a max of 256 characters...
        %h3{:style => "font-size: 16px; color: #999; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;font-weight: 800; letter-spacing: .2px;"} Users
        %table#users_table.table.table-striped.table-bordered.table-hover.table-checkable.order-column
          %thead
            %tr
              %th
                %label.mt-checkbox.mt-checkbox-single.mt-checkbox-outline
                  %input.group-checkable{"data-set" => "#users_table .checkboxes", :type => "checkbox"}/
                  %span
              %th Email
              %th Device Token
              %th Joined
          %tbody
            - User.all.each do |user|
              %tr.odd.gradeX
                %td
                  %label.mt-checkbox.mt-checkbox-single.mt-checkbox-outline
                    = check_box_tag 'tokens[]', user.id, false, :class => 'checkboxes'
                    %span
                %td= user.email
                %td
                  - if user.device_token.present?
                    %span.label.label-sm.label-success Yes
                  - else
                    %span.label.label-sm.label-danger No
                -# %td= user.device_token
                %td{:style => "text-align:center; "}= user.created_at.strftime("%m/%d/%Y")
        .row{:style => "text-align:center"}
          = f.submit "Send", :type => "submit", :class=>"btn btn-primary", :style=>"border-radius: 5px !important; margin-top:10px; background: #FF5252; font-family: 'Muli', 'Helvetica', 'Arial', 'sans-serif'; text-shadow:none; font-variant:none; width: 92%; margin-top:30px"

app/views/notifications/show.html.haml
.col-xs-12.col-lg-8.col-lg-offset-2{:style => " margin-top: 3vh; padding:15px;"}
  .portlet.light
    .portlet-title
      .caption.font-red-sunglo
        %span.caption-subject.bold.uppercase{:style => "font-size:24px"} Push Notification
        %br/
        %small{:style => "font-size:12px; color:gray"}= @notification.created_at.strftime("Sent At: %m/%d/%Y")

    .portlet-body.form
      .form-group.form-md-line-input.form-md-floating-label{:style => "margin-bottom:15px"}
        %input#form_control_1.form-control{:readonly => "readonly", :type => "text", :value => "#{@notification.message}"}/
        %label{:for => "form_control_1"} Message
      .form-group.form-md-line-input.form-md-floating-label{:style => "margin-bottom:15px"}
        %input#form_control_1.form-control{:readonly => "readonly", :type => "text", :value => "#{User.find(@notification.user_id).email}"}/
        %label{:for => "form_control_1"} Sent By
      %h4{:style => "font-size: 13px; color: #999; font-family:verdana, arial, helvetica, sans-serif; font-weight: 400; letter-spacing: 0.5px;"} Sent To
      - @notification.sent_to.each do |id|
        %li{:style=> "margin-left:20px"}= User.find(id).email

      .row.text-center
        = link_to "Go Back", :back, :class => "btn btn-next", :style => "color:white; border-radius: 5px !important; margin-top:10px; background: #FF5252; font-family: 'Muli', 'Helvetica', 'Arial', 'sans-serif'; text-shadow:none; text-decoration:none; width: 92%"
  / END EXAMPLE TABLE PORTLET