config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path_names:{
    sign_up: ''
  }

  resources :users
  resources :notifications

  root to: 'dashboard#index'

  namespace :api do
    mount_devise_token_auth_for 'User', at: 'auth', as: 'users', controllers: {
      sessions: 'users/sessions'
    }
  end

end

app/views/layouts/_menu.html.haml
%nav#mainNav.navbar.navbar-default.navbar-fixed-top.affix
  .container
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        Menu
        %i.fa.fa-bars
      %a.navbar-brand.page-scroll{href: root_path, style: "padding: 5px 0"}
        = image_tag("hti_logo.png", style: "max-height:100%; margin-left: 10px;")
      / Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li
            %li.dropdown
              %a.dropdown-toggle{"data-delay" => "1000", "data-hover" => "dropdown", "data-toggle" => "dropdown", :href => "#"}
                Account
                %span.caret
              %ul.dropdown-menu.dropdown-menu-default{:role => "menu"}
                %li= link_to "Profile", edit_user_registration_path
                %li= link_to "Sign out", destroy_user_session_path, method: :delete
        - else
          %li
            = link_to 'Login', new_session_path(resource_name)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: 'text/html; charset=UTF-8', 'http-equiv' => 'Content-Type'}
    %title HTI | App
    = csrf_meta_tags

    = stylesheet_link_tag 'application', media: 'all'
    %link{href: 'https://fonts.googleapis.com/css?family=Lato', rel: 'stylesheet'}
    %link{href:'https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900', rel: 'stylesheet'}
    %link{href: 'https://fonts.googleapis.com/css?family=Muli', rel: 'stylesheet'}
    %link{href: 'http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all', rel: 'stylesheet', type: 'text/css'}

    = javascript_include_tag 'application'
  %body.main-background{'cz-shortcut-listen' => 'true'}
    = render partial: 'layouts/menu'
    .container{style: 'padding-top: 50px;'}
      - flash.each do |name, msg|
        = content_tag(:div,  msg.kind_of?(Array) ? msg.join(', ') : msg, class: "alert alert-info") if msg.length > 0
      = yield

      :javascript
        window.setTimeout(function () {
             $(".alert-info").slideUp(500, function () {
                  $(".alert-info").hide();
              });
         }, 5000);